import {
  AdminData,
  CustomerData,
  LoanData,
  MarketerData,
  OverviewItems,
  UserDetails,
} from "@/types/types";
import Icon from "./icons";

export const overviewItems: OverviewItems = {
  overviewHead: [
    {
      title: "Total Amount in Loan Collected",
      content: "#150,823,360",
      footer: "₦980,800",
    },
    { title: "Number of Customers", content: "24,743", footer: "" },
    { title: "Monthly acquired customers ", content: "14,743", footer: "" },
    { title: "Acquired customers today ", content: "1,091", footer: "" },
    { title: "Total Number of Loan Collected", content: "104,766", footer: "" },
  ],
  overviewTables: [
    {
      tableName: "Top ranking lenders",
      rows: [
        {
          holder: {
            id: "1",
            icon: Icon.ArrowUp,
            initial: "ER",
            name: "Elina Roberts",
            username: "@eroberts",
          },
          email: "eroberts@gmail.com",
          noOfLoan: "84",
        },
        {
          holder: {
            id: "2",
            icon: Icon.Minus,
            initial: "JD",
            name: "John Dorsi",
            username: "@johndorsi",
          },
          email: "johndorsi297@gmail.com",
          noOfLoan: "67",
        },
        {
          holder: {
            id: "3",
            icon: Icon.ArrowDown,
            initial: "OJ",
            name: "Othello Johnson",
            username: "@otherjohn",
          },
          email: "otherjohn@gmail.com",
          noOfLoan: "63",
        },
        {
          holder: {
            id: "4",
            icon: Icon.ArrowUp,
            initial: "JA",
            name: "James Abdul",
            username: "@jamesa245",
          },
          email: "jamesa245@gmail.com",
          noOfLoan: "54",
        },
        {
          holder: {
            id: "5",
            icon: Icon.ArrowUp,
            initial: "AJ",
            name: "Amie Jackson",
            username: "@ajackson",
          },
          email: "ajackson@gmail.com",
          noOfLoan: "42",
        },
      ],
    },
    {
      tableName: "Highest credit score holders",
      rows: [
        {
          holder: {
            id: "1",
            icon: Icon.Minus,
            initial: "JD",
            name: "John Dorsi",
            username: "@johndorsi",
          },
          email: "johndorsi297@gmail.com",
          score: 354,
        },
        {
          holder: {
            id: "2",
            icon: Icon.ArrowDown,
            initial: "OJ",
            name: "Othello Johnson",
            username: "@otherjohn",
          },
          email: "otherjohn@gmail.com",
          score: 347,
        },
        {
          holder: {
            id: "3",
            icon: Icon.ArrowUp,
            initial: "ER",
            name: "Elina Roberts",
            username: "@eroberts",
          },
          email: "eroberts@gmail.com",
          score: 325,
        },
        {
          holder: {
            id: "4",
            icon: Icon.ArrowUp,
            initial: "JA",
            name: "James Abdul",
            username: "@jamesa245",
          },
          email: "jamesa245@gmail.com",
          score: 318,
        },
        {
          holder: {
            id: "5",
            icon: Icon.Minus,
            initial: "AJ",
            name: "Amie Jackson",
            username: "@ajackson",
          },
          email: "ajackson@gmail.com",
          score: 291,
        },
      ],
    },
  ],
  chartData: {
    // Chart data structure (e.g., for Loan Collection Summary)
    labels: Array.from({ length: 30 }, (_, i) => `${i + 1}th`),
    values: [
      100000, 150000, 130000, 170000, 120000, 200000, 300000, 250000, 180000,
      240000, 280000, 320000,
    ],
  },
};

export const loanData: LoanData = {
  loanHead: [
    { title: "Total number of P2P Loans", content: "#698,725,653", footer: "" },
    {
      title: "Total number of Beta Loans",
      content: "#617,354,900",
      footer: "",
    },
  ],
  loanTableHead: {
    p2p: [
      { header: "Amount", accessor: "amount" },
      { header: "Type", accessor: "type" },
      { header: "Interest", accessor: "interest" },
      { header: "Lender", accessor: "lender" },
      { header: "Borrower", accessor: "borrower" },
      { header: "Loan period", accessor: "loanPeriod" },
    ],
    betaLoans: [
      { header: "Amount", accessor: "amount" },
      { header: "Borrower", accessor: "borrower" },
      { header: "Loan period", accessor: "loanPeriod" },
    ],
  },
  loanTableBody: {
    p2p: [
      {
        id: "1",
        amount: "₦4,000",
        type: "Request",
        interest: "5%",
        lender: "@justinlati",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "2",
        amount: "₦6,000",
        type: "Selection",
        interest: "5%",
        lender: "@justinlati",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "3",
        amount: "₦8,500",
        type: "Request",
        interest: "5%",
        lender: "@justinlati",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "4",
        amount: "₦1,500",
        type: "Selection",
        interest: "5%",
        lender: "@justinlati",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "5",
        amount: "₦500",
        type: "Request",
        interest: "5%",
        lender: "@justinlati",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "6",
        amount: "₦6,800",
        type: "Selection",
        interest: "5%",
        lender: "@justinlati",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "7",
        amount: "₦10,500",
        type: "Request",
        interest: "5%",
        lender: "@justinlati",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "8",
        amount: "₦20,000",
        type: "Selection",
        interest: "5%",
        lender: "@justinlati",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "9",
        amount: "₦2,500",
        type: "Request",
        interest: "5%",
        lender: "@justinlati",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
    ],
    betaLoans: [
      {
        id: "1",
        amount: "₦4,000",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "2",
        amount: "₦6,000",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "3",
        amount: "₦8,500",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "4",
        amount: "₦1,500",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "5",
        amount: "₦500",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "6",
        amount: "₦6,800",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "7",
        amount: "₦10,500",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "8",
        amount: "₦20,000",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "9",
        amount: "₦2,500",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
    ],
  },
};

export const customerData: CustomerData = {
  customerTableHead: {
    p2p: [
      { header: "Name", accessor: "name" },
      { header: "Credit score", accessor: "creditScore" },
      { header: "Loans taken", accessor: "numberOfLoansCollected" },
      { header: "Loans given", accessor: "numberOfLoansGiven" },
    ],
    betaLoans: [
      { header: "Name", accessor: "name" },
      { header: "Credit score", accessor: "creditScore" },
      { header: "Loans taken", accessor: "numberOfLoansCollected" },
    ],
  },
  customerTableBody: {
    p2p: [
      {
        id: "1",
        name: "John Dorsi",
        username: "@johndorsi",
        accountNumber: "0245092345",
        dateJoined: "2024-10-25",
        creditScore: 300,
        status: "active",

        totalAmountBorrowed: 544500,
        highestAmountBorrowed: 65000,
        numberOfLoansCollected: 12,
        lengthOfCreditHistory: 89,
        longestLoanPeriod: "3 weeks",
        shortestLoanPeriod: "1 week",

        totalAmountLent: 1235984,
        highestAmountLent: 350000,
        numberOfLoansGiven: 23,
        longestLendingPeriod: "4 weeks",
        shortestLendingPeriod: "1 week",
      },
      {
        id: "2",
        name: "Sarah Mitchell",
        username: "@sarahmitch",
        accountNumber: "0198765432",
        dateJoined: "2024-09-20",
        creditScore: 385,
        status: "active",

        totalAmountBorrowed: 320000,
        highestAmountBorrowed: 50000,
        numberOfLoansCollected: 8,
        lengthOfCreditHistory: 124,
        longestLoanPeriod: "4 weeks",
        shortestLoanPeriod: "1 week",

        totalAmountLent: 890000,
        highestAmountLent: 200000,
        numberOfLoansGiven: 31,
        longestLendingPeriod: "5 weeks",
        shortestLendingPeriod: "1 week",
      },
      {
        id: "3",
        name: "David Okonkwo",
        username: "@davidoko",
        accountNumber: "0334567890",
        dateJoined: "2024-11-18",
        creditScore: 275,
        status: "active",

        totalAmountBorrowed: 680000,
        highestAmountBorrowed: 85000,
        numberOfLoansCollected: 15,
        lengthOfCreditHistory: 67,
        longestLoanPeriod: "3 weeks",
        shortestLoanPeriod: "1 week",

        totalAmountLent: 450000,
        highestAmountLent: 120000,
        numberOfLoansGiven: 18,
        longestLendingPeriod: "3 weeks",
        shortestLendingPeriod: "1 week",
      },
      {
        id: "4",
        name: "Amaka Johnson",
        username: "@amakaj",
        accountNumber: "0421234567",
        dateJoined: "2024-08-01",
        creditScore: 420,
        status: "active",

        totalAmountBorrowed: 215000,
        highestAmountBorrowed: 40000,
        numberOfLoansCollected: 6,
        lengthOfCreditHistory: 156,
        longestLoanPeriod: "2 weeks",
        shortestLoanPeriod: "1 week",

        totalAmountLent: 1580000,
        highestAmountLent: 400000,
        numberOfLoansGiven: 42,
        longestLendingPeriod: "6 weeks",
        shortestLendingPeriod: "1 week",
      },
      {
        id: "5",
        name: "Emmanuel Adebayo",
        username: "@emmanuela",
        accountNumber: "0567891234",
        dateJoined: "2024-12-10",
        creditScore: 195,
        status: "suspended",

        totalAmountBorrowed: 920000,
        highestAmountBorrowed: 120000,
        numberOfLoansCollected: 22,
        lengthOfCreditHistory: 45,
        longestLoanPeriod: "4 weeks",
        shortestLoanPeriod: "1 week",

        totalAmountLent: 180000,
        highestAmountLent: 60000,
        numberOfLoansGiven: 9,
        longestLendingPeriod: "2 weeks",
        shortestLendingPeriod: "1 week",
      },
      {
        id: "6",
        name: "Chioma Nwosu",
        username: "@chiomann",
        accountNumber: "0654321098",
        dateJoined: "2024-10-15",
        creditScore: 340,
        status: "active",

        totalAmountBorrowed: 410000,
        highestAmountBorrowed: 70000,
        numberOfLoansCollected: 10,
        lengthOfCreditHistory: 98,
        longestLoanPeriod: "3 weeks",
        shortestLoanPeriod: "1 week",

        totalAmountLent: 725000,
        highestAmountLent: 180000,
        numberOfLoansGiven: 25,
        longestLendingPeriod: "4 weeks",
        shortestLendingPeriod: "1 week",
      },
      {
        id: "7",
        name: "Tunde Bakare",
        username: "@tundebak",
        accountNumber: "0712345678",
        dateJoined: "2024-11-13",
        creditScore: 265,
        status: "active",

        totalAmountBorrowed: 550000,
        highestAmountBorrowed: 95000,
        numberOfLoansCollected: 14,
        lengthOfCreditHistory: 72,
        longestLoanPeriod: "5 weeks",
        shortestLoanPeriod: "2 weeks",

        totalAmountLent: 390000,
        highestAmountLent: 110000,
        numberOfLoansGiven: 15,
        longestLendingPeriod: "3 weeks",
        shortestLendingPeriod: "1 week",
      },
      {
        id: "8",
        name: "Fatima Bello",
        username: "@fatimab",
        accountNumber: "0898765432",
        dateJoined: "2024-07-20",
        creditScore: 405,
        status: "active",

        totalAmountBorrowed: 180000,
        highestAmountBorrowed: 35000,
        numberOfLoansCollected: 5,
        lengthOfCreditHistory: 187,
        longestLoanPeriod: "2 weeks",
        shortestLoanPeriod: "1 week",

        totalAmountLent: 2100000,
        highestAmountLent: 500000,
        numberOfLoansGiven: 56,
        longestLendingPeriod: "8 weeks",
        shortestLendingPeriod: "1 week",
      },
      {
        id: "9",
        name: "Oluwaseun Adeola",
        username: "@oluadeola",
        accountNumber: "0923456789",
        dateJoined: "2024-12-02",
        creditScore: 220,
        status: "suspended",

        totalAmountBorrowed: 780000,
        highestAmountBorrowed: 110000,
        numberOfLoansCollected: 18,
        lengthOfCreditHistory: 53,
        longestLoanPeriod: "4 weeks",
        shortestLoanPeriod: "1 week",

        totalAmountLent: 290000,
        highestAmountLent: 80000,
        numberOfLoansGiven: 12,
        longestLendingPeriod: "3 weeks",
        shortestLendingPeriod: "1 week",
      },
    ],
    betaLoans: [
      {
        id: "1",
        name: "Grace Okafor",
        username: "@graceoka",
        accountNumber: "0145678901",
        dateJoined: "2024-10-04",
        creditScore: 310,
        status: "active",

        totalAmountBorrowed: 295000,
        highestAmountBorrowed: 45000,
        numberOfLoansCollected: 7,
        lengthOfCreditHistory: 112,
        longestLoanPeriod: "3 weeks",
        shortestLoanPeriod: "1 week",

        totalAmountLent: 620000,
        highestAmountLent: 150000,
        numberOfLoansGiven: 21,
        longestLendingPeriod: "4 weeks",
        shortestLendingPeriod: "1 week",
      },
      {
        id: "2",
        name: "Ibrahim Musa",
        username: "@ibrahimm",
        accountNumber: "0256789012",
        dateJoined: "2024-11-24",
        creditScore: 245,
        status: "active",

        totalAmountBorrowed: 635000,
        highestAmountBorrowed: 90000,
        numberOfLoansCollected: 16,
        lengthOfCreditHistory: 61,
        longestLoanPeriod: "4 weeks",
        shortestLoanPeriod: "1 week",

        totalAmountLent: 340000,
        highestAmountLent: 95000,
        numberOfLoansGiven: 14,
        longestLendingPeriod: "3 weeks",
        shortestLendingPeriod: "1 week",
      },
      {
        id: "3",
        name: "Blessing Eze",
        username: "@blessingeze",
        accountNumber: "0367890123",
        dateJoined: "2024-09-11",
        creditScore: 370,
        status: "active",

        totalAmountBorrowed: 360000,
        highestAmountBorrowed: 60000,
        numberOfLoansCollected: 9,
        lengthOfCreditHistory: 134,
        longestLoanPeriod: "3 weeks",
        shortestLoanPeriod: "1 week",

        totalAmountLent: 980000,
        highestAmountLent: 250000,
        numberOfLoansGiven: 33,
        longestLendingPeriod: "5 weeks",
        shortestLendingPeriod: "1 week",
      },
      {
        id: "4",
        name: "Kenneth Obi",
        username: "@kennethobi",
        accountNumber: "0478901234",
        dateJoined: "2024-11-02",
        creditScore: 290,
        status: "suspended",

        totalAmountBorrowed: 485000,
        highestAmountBorrowed: 75000,
        numberOfLoansCollected: 11,
        lengthOfCreditHistory: 83,
        longestLoanPeriod: "3 weeks",
        shortestLoanPeriod: "1 week",

        totalAmountLent: 550000,
        highestAmountLent: 140000,
        numberOfLoansGiven: 19,
        longestLendingPeriod: "4 weeks",
        shortestLendingPeriod: "1 week",
      },
      {
        id: "5",
        name: "Ngozi Akinlade",
        username: "@ngoziaki",
        accountNumber: "0589012345",
        dateJoined: "2024-07-05",
        creditScore: 425,
        status: "active",

        totalAmountBorrowed: 150000,
        highestAmountBorrowed: 30000,
        numberOfLoansCollected: 4,
        lengthOfCreditHistory: 203,
        longestLoanPeriod: "2 weeks",
        shortestLoanPeriod: "1 week",

        totalAmountLent: 1750000,
        highestAmountLent: 450000,
        numberOfLoansGiven: 48,
        longestLendingPeriod: "7 weeks",
        shortestLendingPeriod: "1 week",
      },
      {
        id: "6",
        name: "Michael Okoro",
        username: "@mikeokoro",
        accountNumber: "0690123456",
        dateJoined: "2024-11-27",
        creditScore: 255,
        status: "active",

        totalAmountBorrowed: 710000,
        highestAmountBorrowed: 100000,
        numberOfLoansCollected: 17,
        lengthOfCreditHistory: 58,
        longestLoanPeriod: "4 weeks",
        shortestLoanPeriod: "1 week",

        totalAmountLent: 270000,
        highestAmountLent: 75000,
        numberOfLoansGiven: 11,
        longestLendingPeriod: "2 weeks",
        shortestLendingPeriod: "1 week",
      },
      {
        id: "7",
        name: "Aisha Yusuf",
        username: "@aishay",
        accountNumber: "0701234567",
        dateJoined: "2024-10-20",
        creditScore: 335,
        status: "active",

        totalAmountBorrowed: 420000,
        highestAmountBorrowed: 65000,
        numberOfLoansCollected: 10,
        lengthOfCreditHistory: 95,
        longestLoanPeriod: "3 weeks",
        shortestLoanPeriod: "1 week",

        totalAmountLent: 815000,
        highestAmountLent: 190000,
        numberOfLoansGiven: 28,
        longestLendingPeriod: "4 weeks",
        shortestLendingPeriod: "1 week",
      },
      {
        id: "8",
        name: "Chukwudi Nnaji",
        username: "@chukwudinn",
        accountNumber: "0812345678",
        dateJoined: "2024-11-09",
        creditScore: 280,
        status: "active",

        totalAmountBorrowed: 520000,
        highestAmountBorrowed: 80000,
        numberOfLoansCollected: 13,
        lengthOfCreditHistory: 76,
        longestLoanPeriod: "3 weeks",
        shortestLoanPeriod: "1 week",

        totalAmountLent: 435000,
        highestAmountLent: 115000,
        numberOfLoansGiven: 17,
        longestLendingPeriod: "3 weeks",
        shortestLendingPeriod: "1 week",
      },
      {
        id: "9",
        name: "Victoria Adeleke",
        username: "@vickyade",
        accountNumber: "0923456780",
        dateJoined: "2024-08-10",
        creditScore: 395,
        status: "active",

        totalAmountBorrowed: 240000,
        highestAmountBorrowed: 42000,
        numberOfLoansCollected: 6,
        lengthOfCreditHistory: 167,
        longestLoanPeriod: "2 weeks",
        shortestLoanPeriod: "1 week",

        totalAmountLent: 1320000,
        highestAmountLent: 320000,
        numberOfLoansGiven: 38,
        longestLendingPeriod: "6 weeks",
        shortestLendingPeriod: "1 week",
      },
    ],
  },
};

export const adminData: AdminData = {
  adminTableHead: [
    { header: "Name", accessor: "name" },
    { header: "Phone number", accessor: "phoneNumber" },
    { header: "Date added", accessor: "dateAdded" },
  ],
  adminTableBody: [
    {
      id: "1",
      name: "Adam Levi",
      username: "@adamlevi",
      phoneNumber: "+2349825492452",
      email: "adamlevi@gmail.com",
      status: "active",
      dateAdded: "19/04/2024",
      dateJoined: "Apr 12, 2023",
      role: "Super Admin",
    },
    {
      id: "2",
      name: "Chidinma Okafor",
      username: "@chidioka",
      phoneNumber: "+2348092878349",
      email: "chidinma.okafor@gmail.com",
      status: "active",
      dateAdded: "15/03/2024",
      dateJoined: "Mar 08, 2023",
      role: "Admin",
    },
    {
      id: "3",
      name: "Tunde Bakare",
      username: "@tundebak",
      phoneNumber: "+2347065432198",
      email: "tunde.bakare@outlook.com",
      status: "active",
      dateAdded: "22/05/2024",
      dateJoined: "May 18, 2023",
      role: "Moderator",
    },
    {
      id: "4",
      name: "Amina Hassan",
      username: "@aminah",
      phoneNumber: "+2348123456789",
      email: "amina.hassan@yahoo.com",
      status: "inactive",
      dateAdded: "10/02/2024",
      dateJoined: "Jan 25, 2023",
      role: "Admin",
    },
    {
      id: "5",
      name: "Oluwaseun Adeola",
      username: "@seunadeola",
      phoneNumber: "+2349087654321",
      email: "seun.adeola@gmail.com",
      status: "active",
      dateAdded: "08/06/2024",
      dateJoined: "Jun 01, 2023",
      role: "Support Agent",
    },
    {
      id: "6",
      name: "Ibrahim Musa",
      username: "@ibrahimm",
      phoneNumber: "+2348156789012",
      email: "ibrahim.musa@gmail.com",
      status: "inactive",
      dateAdded: "14/01/2024",
      dateJoined: "Dec 10, 2022",
      role: "Moderator",
    },
    {
      id: "7",
      name: "Grace Eze",
      username: "@graceeze",
      phoneNumber: "+2347098765432",
      email: "grace.eze@hotmail.com",
      status: "active",
      dateAdded: "30/07/2024",
      dateJoined: "Jul 22, 2023",
      role: "Admin",
    },
    {
      id: "8",
      name: "Kenneth Obi",
      username: "@kennethy",
      phoneNumber: "+2348134567890",
      email: "kenneth.obi@gmail.com",
      status: "active",
      dateAdded: "25/09/2024",
      dateJoined: "Sep 15, 2023",
      role: "Support Agent",
    },
    {
      id: "9",
      name: "Fatima Bello",
      username: "@fatimab",
      phoneNumber: "+2349012345678",
      email: "fatima.bello@outlook.com",
      status: "inactive",
      dateAdded: "05/11/2023",
      dateJoined: "Oct 28, 2022",
      role: "Moderator",
    },
    {
      id: "10",
      name: "David Okonkwo",
      username: "@davidoko",
      phoneNumber: "+2348076543210",
      email: "david.okonkwo@yahoo.com",
      status: "active",
      dateAdded: "12/08/2024",
      dateJoined: "Aug 05, 2023",
      role: "Admin",
    },
    {
      id: "11",
      name: "Blessing Adebayo",
      username: "@blessingade",
      phoneNumber: "+2347089012345",
      email: "blessing.adebayo@gmail.com",
      status: "active",
      dateAdded: "18/10/2024",
      dateJoined: "Oct 10, 2023",
      role: "Support Agent",
    },
    {
      id: "12",
      name: "Chukwudi Nnaji",
      username: "@chukwudinn",
      phoneNumber: "+2348145678901",
      email: "chukwudi.nnaji@gmail.com",
      status: "inactive",
      dateAdded: "03/12/2023",
      dateJoined: "Nov 20, 2022",
      role: "Moderator",
    },
  ],
};

export const userDetailsData: Record<string, UserDetails> = {
  "1": {
    phoneNumber: "0245092345",
    dateJoined: "2023-05-12",
    highestAmountLent: "₦350,000",
    loansGiven: 23,
    longestLendingPeriod: "4 weeks",
    shortestLendingPeriod: "1 week",
    totalAmountBorrowed: "₦544,500",
    highestAmountBorrowed: "₦65,000",
    loansCollected: 12,
    creditHistoryLength: "89 days",
    longestLoanPeriod: "3 weeks",
    shortestLoanPeriod: "1 week",
    creditScore: 300,
  },
};

export const marketerData: MarketerData = {
  marketerTableHead: [
    { header: "Marketing partners", accessor: "name" },
    { header: "Total revenue", accessor: "totalRevenue" },
    { header: "Total no. of customers added", accessor: "totalCustomers" },
    { header: "Active customers", accessor: "activeCustomers" },
    { header: "Monthly customers", accessor: "monthlyCustomers" },
  ],
  marketerTableBody: [
    {
      id: "1",
      name: "Range Media",
      username: "@range",
      totalRevenue: 120000,
      totalCustomers: 340,
      activeCustomers: 290,
      monthlyCustomers: 45,
      isActive: true,
    },
    {
      id: "2",
      name: "Apex Marketing Solutions",
      username: "@apexmkt",
      totalRevenue: 85000,
      totalCustomers: 215,
      activeCustomers: 180,
      monthlyCustomers: 32,
      isActive: true,
    },
    {
      id: "3",
      name: "Digital Reach Hub",
      username: "@digitalreach",
      totalRevenue: 156000,
      totalCustomers: 425,
      activeCustomers: 380,
      monthlyCustomers: 58,
      isActive: true,
    },
    {
      id: "4",
      name: "Growth Partners NG",
      username: "@growthng",
      totalRevenue: 42000,
      totalCustomers: 128,
      activeCustomers: 95,
      monthlyCustomers: 18,
      isActive: false,
    },
    {
      id: "5",
      name: "Prime Connect",
      username: "@primeconnect",
      totalRevenue: 198000,
      totalCustomers: 520,
      activeCustomers: 475,
      monthlyCustomers: 72,
      isActive: true,
    },
    {
      id: "6",
      name: "Velocity Promotions",
      username: "@velocitypro",
      totalRevenue: 67000,
      totalCustomers: 185,
      activeCustomers: 142,
      monthlyCustomers: 24,
      isActive: true,
    },
    {
      id: "7",
      name: "Metro Advertising",
      username: "@metroadz",
      totalRevenue: 31000,
      totalCustomers: 92,
      activeCustomers: 68,
      monthlyCustomers: 12,
      isActive: false,
    },
    {
      id: "8",
      name: "Spark Media Group",
      username: "@sparkmedia",
      totalRevenue: 142000,
      totalCustomers: 380,
      activeCustomers: 340,
      monthlyCustomers: 51,
      isActive: true,
    },
    {
      id: "9",
      name: "Horizon Marketing",
      username: "@horizonmkt",
      totalRevenue: 93000,
      totalCustomers: 245,
      activeCustomers: 210,
      monthlyCustomers: 35,
      isActive: true,
    },
    {
      id: "10",
      name: "Zenith Outreach",
      username: "@zenithout",
      totalRevenue: 178000,
      totalCustomers: 465,
      activeCustomers: 420,
      monthlyCustomers: 64,
      isActive: true,
    },
    {
      id: "11",
      name: "Pulse Advertising",
      username: "@pulseadz",
      totalRevenue: 55000,
      totalCustomers: 156,
      activeCustomers: 125,
      monthlyCustomers: 21,
      isActive: true,
    },
    {
      id: "12",
      name: "Impact Marketing Co",
      username: "@impactmkt",
      totalRevenue: 24000,
      totalCustomers: 78,
      activeCustomers: 52,
      monthlyCustomers: 8,
      isActive: false,
    },
  ],
};

export const customerTableHeader: Array<{
  header: string;
  accessor: keyof ICustomersResponse["items"][0];
}> = [
  { header: "Name", accessor: "name" },
  { header: "Credit score", accessor: "creditScore" },
  { header: "Total Loans ", accessor: "totalLoans" },
  { header: "Joined at", accessor: "createdAt" },
];
