import {
  AdminData,
  CustomerData,
  LoanData,
  OverviewItems,
  UserDetails,
} from "@/types/types";
import Icon from "./icons";

export const overviewItems: OverviewItems = {
  overviewHead: [
    {
      title: "Total Amount in Loan Collected",
      content: "#150,823,360",
      footer: "#980,800",
    },
    { title: "Number of Customers", content: "24,743", footer: "" },
    { title: "Total Number of Loan Collected", content: "104,766", footer: "" },
  ],
  overviewTables: [
    {
      tableName: "Top ranking lenders",
      rows: [
        {
          holder: {
            id: "1",
            icon: Icon.ArrowUp,
            initial: "ER",
            name: "Elina Roberts",
            username: "@eroberts",
          },
          email: "eroberts@gmail.com",
          noOfLoan: "84",
        },
        {
          holder: {
            id: "2",
            icon: Icon.Minus,
            initial: "JD",
            name: "John Dorsi",
            username: "@johndorsi",
          },
          email: "johndorsi297@gmail.com",
          noOfLoan: "67",
        },
        {
          holder: {
            id: "3",
            icon: Icon.ArrowDown,
            initial: "OJ",
            name: "Othello Johnson",
            username: "@otherjohn",
          },
          email: "otherjohn@gmail.com",
          noOfLoan: "63",
        },
        {
          holder: {
            id: "4",
            icon: Icon.ArrowUp,
            initial: "JA",
            name: "James Abdul",
            username: "@jamesa245",
          },
          email: "jamesa245@gmail.com",
          noOfLoan: "54",
        },
        {
          holder: {
            id: "5",
            icon: Icon.ArrowUp,
            initial: "AJ",
            name: "Amie Jackson",
            username: "@ajackson",
          },
          email: "ajackson@gmail.com",
          noOfLoan: "42",
        },
      ],
    },
    {
      tableName: "Highest credit score holders",
      rows: [
        {
          holder: {
            id: "1",
            icon: Icon.Minus,
            initial: "JD",
            name: "John Dorsi",
            username: "@johndorsi",
          },
          email: "johndorsi297@gmail.com",
          score: 354,
        },
        {
          holder: {
            id: "2",
            icon: Icon.ArrowDown,
            initial: "OJ",
            name: "Othello Johnson",
            username: "@otherjohn",
          },
          email: "otherjohn@gmail.com",
          score: 347,
        },
        {
          holder: {
            id: "3",
            icon: Icon.ArrowUp,
            initial: "ER",
            name: "Elina Roberts",
            username: "@eroberts",
          },
          email: "eroberts@gmail.com",
          score: 325,
        },
        {
          holder: {
            id: "4",
            icon: Icon.ArrowUp,
            initial: "JA",
            name: "James Abdul",
            username: "@jamesa245",
          },
          email: "jamesa245@gmail.com",
          score: 318,
        },
        {
          holder: {
            id: "5",
            icon: Icon.Minus,
            initial: "AJ",
            name: "Amie Jackson",
            username: "@ajackson",
          },
          email: "ajackson@gmail.com",
          score: 291,
        },
      ],
    },
  ],
  chartData: {
    // Chart data structure (e.g., for Loan Collection Summary)
    labels: Array.from({ length: 30 }, (_, i) => `${i + 1}th`),
    values: [
      100000, 150000, 130000, 170000, 120000, 200000, 300000, 250000, 180000,
      240000, 280000, 320000,
    ],
  },
};

export const loanData: LoanData = {
  loanHead: [
    { title: "Total number of P2P Loans", content: "#698,725,653", footer: "" },
    {
      title: "Total number of Beta Loans",
      content: "#617,354,900",
      footer: "",
    },
  ],
  loanTableHead: {
    p2p: [
      { header: "Amount", accessor: "amount" },
      { header: "Type", accessor: "type" },
      { header: "Interest", accessor: "interest" },
      { header: "Lender", accessor: "lender" },
      { header: "Borrower", accessor: "borrower" },
      { header: "Loan period", accessor: "loanPeriod" },
    ],
    betaLoans: [
      { header: "Amount", accessor: "amount" },
      { header: "Borrower", accessor: "borrower" },
      { header: "Loan period", accessor: "loanPeriod" },
    ],
  },
  loanTableBody: {
    p2p: [
      {
        id: "1",
        amount: "₦4,000",
        type: "Request",
        interest: "5%",
        lender: "@justinlati",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "2",
        amount: "₦6,000",
        type: "Selection",
        interest: "5%",
        lender: "@justinlati",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "3",
        amount: "₦8,500",
        type: "Request",
        interest: "5%",
        lender: "@justinlati",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "4",
        amount: "₦1,500",
        type: "Selection",
        interest: "5%",
        lender: "@justinlati",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "5",
        amount: "₦500",
        type: "Request",
        interest: "5%",
        lender: "@justinlati",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "6",
        amount: "₦6,800",
        type: "Selection",
        interest: "5%",
        lender: "@justinlati",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "7",
        amount: "₦10,500",
        type: "Request",
        interest: "5%",
        lender: "@justinlati",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "8",
        amount: "₦20,000",
        type: "Selection",
        interest: "5%",
        lender: "@justinlati",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "9",
        amount: "₦2,500",
        type: "Request",
        interest: "5%",
        lender: "@justinlati",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
    ],
    betaLoans: [
      {
        id: "1",
        amount: "₦4,000",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "2",
        amount: "₦6,000",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "3",
        amount: "₦8,500",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "4",
        amount: "₦1,500",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "5",
        amount: "₦500",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "6",
        amount: "₦6,800",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "7",
        amount: "₦10,500",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "8",
        amount: "₦20,000",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
      {
        id: "9",
        amount: "₦2,500",
        borrower: "@johndorsi",
        loanPeriod: "2 weeks",
      },
    ],
  },
};

export const customerData: CustomerData = {
  customerTableHead: {
    p2p: [
      { header: "Name", accessor: "name" },
      { header: "Credit score", accessor: "creditScore" },
      { header: "Loans taken", accessor: "loansTaken" },
      { header: "Loans given", accessor: "loansGiven" },
    ],
    betaLoans: [
      { header: "Name", accessor: "name" },
      { header: "Credit score", accessor: "creditScore" },
      { header: "Loans taken", accessor: "loansTaken" },
    ],
  },
  customerTableBody: {
    p2p: [
      {
        id: "1",
        name: "John Dorsi",
        username: "@johndorsi",
        creditScore: 382,
        loansTaken: "38",
        loansGiven: "72",
      },
      {
        id: "2",
        name: "John Dorsi",
        username: "@johndorsi",
        creditScore: 141,
        loansTaken: "2 weeks",
        loansGiven: "2 weeks",
      },
      {
        id: "3",
        name: "Leading text",
        username: "@johndorsi",
        creditScore: 282,
        loansTaken: "2 weeks",
        loansGiven: "2 weeks",
      },
      {
        id: "4",
        name: "Leading text",
        username: "@johndorsi",
        creditScore: 241,
        loansTaken: "2 weeks",
        loansGiven: "2 weeks",
      },
      {
        id: "5",
        name: "Leading text",
        username: "@johndorsi",
        creditScore: 134,
        loansTaken: "2 weeks",
        loansGiven: "2 weeks",
      },
      {
        id: "6",
        name: "Leading text",
        username: "@johndorsi",
        creditScore: 248,
        loansTaken: "2 weeks",
        loansGiven: "2 weeks",
      },
      {
        id: "7",
        name: "Leading text",
        username: "@johndorsi",
        creditScore: 143,
        loansTaken: "2 weeks",
        loansGiven: "2 weeks",
      },
      {
        id: "8",
        name: "Leading text",
        username: "@johndorsi",
        creditScore: 244,
        loansTaken: "2 weeks",
        loansGiven: "2 weeks",
      },
      {
        id: "9",
        name: "Leading text",
        username: "@johndorsi",
        creditScore: 134,
        loansTaken: "2 weeks",
        loansGiven: "2 weeks",
      },
    ],
    betaLoans: [
      {
        id: "1",
        name: "John Dorsi",
        username: "@johndorsi",
        creditScore: 141,
        loansTaken: "2 weeks",
        loansGiven: "2 weeks",
      },
      {
        id: "2",
        name: "Leading text",
        username: "@johndorsi",
        creditScore: 134,
        loansTaken: "2 weeks",
        loansGiven: "2 weeks",
      },
      {
        id: "3",
        name: "Leading text",
        username: "@johndorsi",
        creditScore: 144,
        loansTaken: "2 weeks",
        loansGiven: "2 weeks",
      },
      {
        id: "4",
        name: "Leading text",
        username: "@johndorsi",
        creditScore: 168,
        loansTaken: "2 weeks",
        loansGiven: "2 weeks",
      },
      {
        id: "5",
        name: "Leading text",
        username: "@johndorsi",
        creditScore: 190,
        loansTaken: "2 weeks",
        loansGiven: "2 weeks",
      },
      {
        id: "6",
        name: "Leading text",
        username: "@johndorsi",
        creditScore: 234,
        loansTaken: "2 weeks",
        loansGiven: "2 weeks",
      },
      {
        id: "7",
        name: "Leading text",
        username: "@johndorsi",
        creditScore: 234,
        loansTaken: "2 weeks",
        loansGiven: "2 weeks",
      },
      {
        id: "8",
        name: "Leading text",
        username: "@johndorsi",
        creditScore: 250,
        loansTaken: "2 weeks",
        loansGiven: "2 weeks",
      },
      {
        id: "9",
        name: "Leading text",
        username: "@johndorsi",
        creditScore: 298,
        loansTaken: "2 weeks",
        loansGiven: "2 weeks",
      },
    ],
  },
};

export const adminData: AdminData = {
  adminTableHead: [
      { header: "Name", accessor: "name" },
      { header: "Phone number", accessor: "phoneNumber" },
      { header: "Date added", accessor: "dateAdded" },
  ],
  adminTableBody: [
      {
        id: "1",
        name: "Adam Levi",
        username: "@adamlevi",
        phoneNumber: "+2349825492452",
        email: "adamlevi@gmail.com",
        status: "active",
        dateAdded: "19/04/2024",
        dateJoined: "Apr 12, 2023",
        highestAmountLent: "₦500,000",
        loansGiven: 72,
        longestLendingPeriod: "6 months",
        shortestLendingPeriod: "2 weeks",
        totalAmountBorrowed: "₦1,200,000",
        highestAmountBorrowed: "₦300,000",
        loansCollected: 38,
        creditHistoryLength: "2 years",
        longestLoanPeriod: "1 year",
        shortestLoanPeriod: "2 weeks",
        creditScore: 382,
      },
      {
        id: "2",
        name: "John Dorsi",
        username: "@johndorsi",
        phoneNumber: "+2348092878349",
        email: "johndorsi@gmail.com",
        status: "active",
        dateAdded: "18/04/2024",
        dateJoined: "Mar 15, 2023",
        highestAmountLent: "₦200,000",
        loansGiven: 15,
        longestLendingPeriod: "3 months",
        shortestLendingPeriod: "1 month",
        totalAmountBorrowed: "₦800,000",
        highestAmountBorrowed: "₦200,000",
        loansCollected: 20,
        creditHistoryLength: "1 year",
        longestLoanPeriod: "8 months",
        shortestLoanPeriod: "2 weeks",
        creditScore: 141,
      },
      {
        id: "2",
        name: "John Dorsi",
        username: "@johndorsi",
        phoneNumber: "+2348092878349",
        email: "johndorsi@gmail.com",
        status: "active",
        dateAdded: "18/04/2024",
        dateJoined: "Mar 15, 2023",
        highestAmountLent: "₦200,000",
        loansGiven: 15,
        longestLendingPeriod: "3 months",
        shortestLendingPeriod: "1 month",
        totalAmountBorrowed: "₦800,000",
        highestAmountBorrowed: "₦200,000",
        loansCollected: 20,
        creditHistoryLength: "1 year",
        longestLoanPeriod: "8 months",
        shortestLoanPeriod: "2 weeks",
        creditScore: 141,
      },
      {
        id: "2",
        name: "John Dorsi",
        username: "@johndorsi",
        phoneNumber: "+2348092878349",
        email: "johndorsi@gmail.com",
        status: "active",
        dateAdded: "18/04/2024",
        dateJoined: "Mar 15, 2023",
        highestAmountLent: "₦200,000",
        loansGiven: 15,
        longestLendingPeriod: "3 months",
        shortestLendingPeriod: "1 month",
        totalAmountBorrowed: "₦800,000",
        highestAmountBorrowed: "₦200,000",
        loansCollected: 20,
        creditHistoryLength: "1 year",
        longestLoanPeriod: "8 months",
        shortestLoanPeriod: "2 weeks",
        creditScore: 141,
      },
      {
        id: "2",
        name: "John Dorsi",
        username: "@johndorsi",
        phoneNumber: "+2348092878349",
        email: "johndorsi@gmail.com",
        status: "active",
        dateAdded: "18/04/2024",
        dateJoined: "Mar 15, 2023",
        highestAmountLent: "₦200,000",
        loansGiven: 15,
        longestLendingPeriod: "3 months",
        shortestLendingPeriod: "1 month",
        totalAmountBorrowed: "₦800,000",
        highestAmountBorrowed: "₦200,000",
        loansCollected: 20,
        creditHistoryLength: "1 year",
        longestLoanPeriod: "8 months",
        shortestLoanPeriod: "2 weeks",
        creditScore: 141,
      },
      {
        id: "2",
        name: "John Dorsi",
        username: "@johndorsi",
        phoneNumber: "+2348092878349",
        email: "johndorsi@gmail.com",
        status: "active",
        dateAdded: "18/04/2024",
        dateJoined: "Mar 15, 2023",
        highestAmountLent: "₦200,000",
        loansGiven: 15,
        longestLendingPeriod: "3 months",
        shortestLendingPeriod: "1 month",
        totalAmountBorrowed: "₦800,000",
        highestAmountBorrowed: "₦200,000",
        loansCollected: 20,
        creditHistoryLength: "1 year",
        longestLoanPeriod: "8 months",
        shortestLoanPeriod: "2 weeks",
        creditScore: 141,
      },
      {
        id: "2",
        name: "John Dorsi",
        username: "@johndorsi",
        phoneNumber: "+2348092878349",
        email: "johndorsi@gmail.com",
        status: "active",
        dateAdded: "18/04/2024",
        dateJoined: "Mar 15, 2023",
        highestAmountLent: "₦200,000",
        loansGiven: 15,
        longestLendingPeriod: "3 months",
        shortestLendingPeriod: "1 month",
        totalAmountBorrowed: "₦800,000",
        highestAmountBorrowed: "₦200,000",
        loansCollected: 20,
        creditHistoryLength: "1 year",
        longestLoanPeriod: "8 months",
        shortestLoanPeriod: "2 weeks",
        creditScore: 141,
      },
      {
        id: "2",
        name: "John Dorsi",
        username: "@johndorsi",
        phoneNumber: "+2348092878349",
        email: "johndorsi@gmail.com",
        status: "active",
        dateAdded: "18/04/2024",
        dateJoined: "Mar 15, 2023",
        highestAmountLent: "₦200,000",
        loansGiven: 15,
        longestLendingPeriod: "3 months",
        shortestLendingPeriod: "1 month",
        totalAmountBorrowed: "₦800,000",
        highestAmountBorrowed: "₦200,000",
        loansCollected: 20,
        creditHistoryLength: "1 year",
        longestLoanPeriod: "8 months",
        shortestLoanPeriod: "2 weeks",
        creditScore: 141,
      },
      {
        id: "2",
        name: "John Dorsi",
        username: "@johndorsi",
        phoneNumber: "+2348092878349",
        email: "johndorsi@gmail.com",
        status: "active",
        dateAdded: "18/04/2024",
        dateJoined: "Mar 15, 2023",
        highestAmountLent: "₦200,000",
        loansGiven: 15,
        longestLendingPeriod: "3 months",
        shortestLendingPeriod: "1 month",
        totalAmountBorrowed: "₦800,000",
        highestAmountBorrowed: "₦200,000",
        loansCollected: 20,
        creditHistoryLength: "1 year",
        longestLoanPeriod: "8 months",
        shortestLoanPeriod: "2 weeks",
        creditScore: 141,
      },
      {
        id: "2",
        name: "John Dorsi",
        username: "@johndorsi",
        phoneNumber: "+2348092878349",
        email: "johndorsi@gmail.com",
        status: "active",
        dateAdded: "18/04/2024",
        dateJoined: "Mar 15, 2023",
        highestAmountLent: "₦200,000",
        loansGiven: 15,
        longestLendingPeriod: "3 months",
        shortestLendingPeriod: "1 month",
        totalAmountBorrowed: "₦800,000",
        highestAmountBorrowed: "₦200,000",
        loansCollected: 20,
        creditHistoryLength: "1 year",
        longestLoanPeriod: "8 months",
        shortestLoanPeriod: "2 weeks",
        creditScore: 141,
      },

    ],
};


export const userDetailsData: Record<string, UserDetails> = {
  "1": {
    phoneNumber: "0245092345",
    dateJoined: "2023-05-12",
    highestAmountLent: "₦350,000",
    loansGiven: 23,
    longestLendingPeriod: "4 weeks",
    shortestLendingPeriod: "1 week",
    totalAmountBorrowed: "₦544,500",
    highestAmountBorrowed: "₦65,000",
    loansCollected: 12,
    creditHistoryLength: "89 days",
    longestLoanPeriod: "3 weeks",
    shortestLoanPeriod: "1 week",
    creditScore: 300,
  },
};
